name: mne-connectivity
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - numpy
  - scipy
  - xarray
  - matplotlib-base
  - tqdm
  - pooch>=1.5
  - decorator
  - h5io
  - pandas
  - pillow
  - statsmodels
  - joblib
  - vtk>=9.0.1
  - pyvista>=0.32,!=0.35.2,!=0.38.0,!=0.38.1,!=0.38.2,!=0.38.3,!=0.38.4,!=0.38.5
  - pyvistaqt>=0.4
  - qtpy
  - mne-base>=1.6
  - h5netcdf
  - pyside6
  - numba>=0.55.0
