name: 'macos / conda'
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  job:
    name: 'py3.6'
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.7'
          auto-update-conda: true
          environment-file: 'environment.yml'
          activate-environment: 'mne_realtime'
        name: 'Setup conda'
      - shell: bash -el {0}
        run: ./tools/pip_dependencies.sh
        name: 'Install MNE-Realtime'
      - shell: bash -el {0}
        run: mne sys_info
        name: Print config
      - shell: bash -el {0}
        run: python -c "import mne; print(mne.datasets.testing.data_path(verbose=True))"
        name: 'Get test data'
      - shell: bash -el {0}
        run: pytest mne_realtime
        name: 'Run tests'
      - uses: codecov/codecov-action@v1
        if: success()
        name: 'Upload coverage to CodeCov'
